// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RamApi.Data;

#nullable disable

namespace RamApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260326112730_AddOrderEmail")]
    partial class AddOrderEmail
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("RamApi.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OrderedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RamId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RamId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("RamApi.Models.Ram", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CapacityGb")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DdrType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("SpeedMhz")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Stock")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Warranty")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Rams");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Kingston",
                            CapacityGb = 8,
                            DdrType = "DDR4",
                            Description = "",
                            Name = "Fury Beast DDR4",
                            Price = 2499m,
                            SpeedMhz = 3200,
                            Stock = 10,
                            Warranty = "Lifetime"
                        },
                        new
                        {
                            Id = 2,
                            Brand = "Kingston",
                            CapacityGb = 16,
                            DdrType = "DDR4",
                            Description = "",
                            Name = "Fury Beast DDR4",
                            Price = 4599m,
                            SpeedMhz = 3200,
                            Stock = 8,
                            Warranty = "Lifetime"
                        },
                        new
                        {
                            Id = 3,
                            Brand = "Corsair",
                            CapacityGb = 8,
                            DdrType = "DDR4",
                            Description = "",
                            Name = "Vengeance LPX",
                            Price = 2299m,
                            SpeedMhz = 3000,
                            Stock = 5,
                            Warranty = "Lifetime"
                        },
                        new
                        {
                            Id = 4,
                            Brand = "Corsair",
                            CapacityGb = 16,
                            DdrType = "DDR4",
                            Description = "",
                            Name = "Vengeance LPX",
                            Price = 4299m,
                            SpeedMhz = 3000,
                            Stock = 0,
                            Warranty = "Lifetime"
                        },
                        new
                        {
                            Id = 5,
                            Brand = "G.Skill",
                            CapacityGb = 16,
                            DdrType = "DDR4",
                            Description = "",
                            Name = "Trident Z RGB",
                            Price = 5499m,
                            SpeedMhz = 3600,
                            Stock = 6,
                            Warranty = "Lifetime"
                        },
                        new
                        {
                            Id = 6,
                            Brand = "G.Skill",
                            CapacityGb = 32,
                            DdrType = "DDR5",
                            Description = "",
                            Name = "Trident Z5 RGB",
                            Price = 12999m,
                            SpeedMhz = 6000,
                            Stock = 4,
                            Warranty = "Lifetime"
                        },
                        new
                        {
                            Id = 7,
                            Brand = "G.Skill",
                            CapacityGb = 8,
                            DdrType = "DDR4",
                            Description = "",
                            Name = "Ripjaws V",
                            Price = 2199m,
                            SpeedMhz = 3200,
                            Stock = 12,
                            Warranty = "Lifetime"
                        },
                        new
                        {
                            Id = 8,
                            Brand = "G.Skill",
                            CapacityGb = 16,
                            DdrType = "DDR4",
                            Description = "",
                            Name = "Ripjaws V",
                            Price = 4099m,
                            SpeedMhz = 3200,
                            Stock = 7,
                            Warranty = "Lifetime"
                        },
                        new
                        {
                            Id = 9,
                            Brand = "Crucial",
                            CapacityGb = 8,
                            DdrType = "DDR4",
                            Description = "",
                            Name = "Ballistix Sport",
                            Price = 1999m,
                            SpeedMhz = 2666,
                            Stock = 0,
                            Warranty = "Lifetime"
                        },
                        new
                        {
                            Id = 10,
                            Brand = "Crucial",
                            CapacityGb = 16,
                            DdrType = "DDR5",
                            Description = "",
                            Name = "Pro DDR5",
                            Price = 7499m,
                            SpeedMhz = 5600,
                            Stock = 3,
                            Warranty = "5 Years"
                        },
                        new
                        {
                            Id = 11,
                            Brand = "ADATA",
                            CapacityGb = 16,
                            DdrType = "DDR5",
                            Description = "",
                            Name = "XPG Lancer",
                            Price = 6999m,
                            SpeedMhz = 5200,
                            Stock = 5,
                            Warranty = "Lifetime"
                        },
                        new
                        {
                            Id = 12,
                            Brand = "ADATA",
                            CapacityGb = 16,
                            DdrType = "DDR4",
                            Description = "",
                            Name = "XPG Spectrix D50",
                            Price = 5199m,
                            SpeedMhz = 3600,
                            Stock = 9,
                            Warranty = "Lifetime"
                        },
                        new
                        {
                            Id = 13,
                            Brand = "Corsair",
                            CapacityGb = 32,
                            DdrType = "DDR5",
                            Description = "",
                            Name = "Dominator Platinum",
                            Price = 14999m,
                            SpeedMhz = 5600,
                            Stock = 2,
                            Warranty = "Lifetime"
                        },
                        new
                        {
                            Id = 14,
                            Brand = "TeamGroup",
                            CapacityGb = 8,
                            DdrType = "DDR4",
                            Description = "",
                            Name = "T-Force Vulcan Z",
                            Price = 1899m,
                            SpeedMhz = 3200,
                            Stock = 15,
                            Warranty = "Lifetime"
                        },
                        new
                        {
                            Id = 15,
                            Brand = "TeamGroup",
                            CapacityGb = 16,
                            DdrType = "DDR4",
                            Description = "",
                            Name = "T-Force Delta RGB",
                            Price = 3999m,
                            SpeedMhz = 3200,
                            Stock = 0,
                            Warranty = "Lifetime"
                        });
                });

            modelBuilder.Entity("RamApi.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RamId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Rating")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RamId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("RamApi.Models.Order", b =>
                {
                    b.HasOne("RamApi.Models.Ram", "Ram")
                        .WithMany()
                        .HasForeignKey("RamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ram");
                });

            modelBuilder.Entity("RamApi.Models.Review", b =>
                {
                    b.HasOne("RamApi.Models.Ram", "Ram")
                        .WithMany()
                        .HasForeignKey("RamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ram");
                });
#pragma warning restore 612, 618
        }
    }
}
